"""criando tabela produto

Revision ID: 502dfc361778
Revises: 
Create Date: 2026-02-13 21:00:32.398286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502dfc361778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('prece', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
