"""atualizando a tabela produto

Revision ID: 81326884a8f1
Revises: 502dfc361778
Create Date: 2026-02-13 21:05:02.988855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81326884a8f1'
down_revision = '502dfc361778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=False))
        batch_op.drop_column('prece')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prece', sa.FLOAT(), nullable=False))
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
