"""Criando tabelas

Revision ID: a4475ca729cb
Revises: 5f8445794c7d
Create Date: 2026-02-16 16:57:59.056078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4475ca729cb'
down_revision = '5f8445794c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    op.drop_table('produto')
    # ### end Alembic commands ###
